// AUTO-GENERATED by scripts/gen_icon_ink.py from resources/icons/icons.png
// -- do not edit by hand; rerun it when the atlas changes (source_checks
// fails while this is stale).
//
// Each icon's INK box inside its atlas cell (alpha >= 128), so a mark can be
// sized by the ink a design measures rather than by its box
// (afterhours_gaps.md #114).
#pragma once
#include <array>
#include <string_view>

namespace hanabi::icons {

struct InkEntry {
    std::string_view name;
    int cell;               // the cell's side, in atlas pixels
    int x, y, w, h;         // the ink box, in atlas pixels, inside the cell
};

inline constexpr std::array<InkEntry, 37> kInk = {{
    {"brand", 32, 3, 3, 26, 26},
    {"gear", 32, 4, 3, 24, 26},
    {"plus", 32, 3, 3, 26, 26},
    {"search", 32, 3, 3, 26, 26},
    {"sidebar_close", 32, 3, 3, 26, 26},
    {"sidebar_open", 32, 3, 3, 26, 26},
    {"chevron_down", 32, 3, 8, 26, 15},
    {"home", 32, 3, 3, 25, 26},
    {"blocked", 32, 3, 3, 26, 26},
    {"review", 32, 3, 6, 26, 19},
    {"star", 32, 3, 3, 26, 25},
    {"folder_grid", 32, 3, 3, 26, 26},
    {"fold_all", 32, 7, 3, 18, 26},
    {"clock", 32, 3, 3, 26, 26},
    {"automated", 32, 4, 3, 24, 26},
    {"close", 32, 3, 3, 26, 26},
    {"archive", 32, 3, 4, 26, 24},
    {"layers", 32, 3, 3, 26, 26},
    {"hand", 32, 3, 3, 26, 26},
    {"check_circle", 32, 3, 3, 26, 26},
    {"pin", 32, 6, 3, 19, 26},
    {"panel_left", 32, 3, 3, 26, 26},
    {"sliders", 32, 3, 3, 26, 26},
    {"subagents", 32, 3, 3, 26, 26},
    {"node", 32, 3, 3, 26, 26},
    {"skills", 32, 3, 3, 26, 26},
    {"checklist", 32, 3, 6, 26, 21},
    {"paperclip", 32, 4, 3, 25, 26},
    {"paintbrush", 32, 3, 3, 26, 26},
    {"chat_bubbles", 32, 3, 3, 26, 26},
    {"bell", 32, 4, 3, 24, 26},
    {"drive", 32, 3, 6, 26, 21},
    {"network", 32, 3, 3, 26, 26},
    {"cpu", 32, 3, 3, 26, 26},
    {"keyboard", 32, 3, 6, 26, 21},
    {"list_plus", 32, 3, 6, 26, 21},
    {"info", 32, 3, 3, 26, 26},
}};

inline constexpr const InkEntry* ink_of(std::string_view name) {
    for (const InkEntry& e : kInk)
        if (e.name == name) return &e;
    return nullptr;
}

// The draw_px that makes `name`'s ink `inkPx` tall (or wide, when `wide`):
// one step instead of build, shoot, measure, scale, rebuild. An unknown
// name answers `inkPx` (box = ink, the old assumption).
inline constexpr float draw_px_for_ink(std::string_view name, float inkPx, bool wide = false) {
    const InkEntry* e = ink_of(name);
    if (e == nullptr) return inkPx;
    const int ink = wide ? e->w : e->h;
    if (ink <= 0) return inkPx;
    return inkPx * static_cast<float>(e->cell) / static_cast<float>(ink);
}

// What a SCREENSHOT measures is wider than the core ink: the atlas is
// sampled down bilinearly, so partial coverage spreads about 0.75 pt past each
// edge. Calibrated on the two close-mark captures afterhours_gaps.md #114
// records (draw 11 -> 10-11 px visible; draw 8 -> 8 px), +-1 px. The draw_px
// whose VISIBLE extent is `extentPx`:
inline constexpr float kSampleSpreadPx = 1.5f;
inline constexpr float draw_px_for_extent(std::string_view name, float extentPx, bool wide = false) {
    const float core = extentPx - kSampleSpreadPx;
    return draw_px_for_ink(name, core > 1.0f ? core : 1.0f, wide);
}

}  // namespace hanabi::icons
