// AUTO-GENERATED by scripts/gen_icons.py — do not edit by hand.
// Lucide (ISC) chrome-icon atlas: name -> source rect in icons.png.
#pragma once
#include <array>
#include <string_view>

namespace hanabi::icons {

struct AtlasEntry { std::string_view name; float x, y, w, h; };

inline constexpr int kSheetWidth  = 128;
inline constexpr int kSheetHeight = 192;
inline constexpr int kCell        = 32;

inline constexpr std::array<AtlasEntry, 22> kAtlas = {{
    {"brand", 0.f, 0.f, 32.f, 32.f},
    {"gear", 32.f, 0.f, 32.f, 32.f},
    {"plus", 64.f, 0.f, 32.f, 32.f},
    {"search", 96.f, 0.f, 32.f, 32.f},
    {"sidebar_close", 0.f, 32.f, 32.f, 32.f},
    {"sidebar_open", 32.f, 32.f, 32.f, 32.f},
    {"chevron_down", 64.f, 32.f, 32.f, 32.f},
    {"home", 96.f, 32.f, 32.f, 32.f},
    {"blocked", 0.f, 64.f, 32.f, 32.f},
    {"review", 32.f, 64.f, 32.f, 32.f},
    {"star", 64.f, 64.f, 32.f, 32.f},
    {"folder_grid", 96.f, 64.f, 32.f, 32.f},
    {"fold_all", 0.f, 96.f, 32.f, 32.f},
    {"clock", 32.f, 96.f, 32.f, 32.f},
    {"automated", 64.f, 96.f, 32.f, 32.f},
    {"close", 96.f, 96.f, 32.f, 32.f},
    {"archive", 0.f, 128.f, 32.f, 32.f},
    {"layers", 32.f, 128.f, 32.f, 32.f},
    {"hand", 64.f, 128.f, 32.f, 32.f},
    {"check_circle", 96.f, 128.f, 32.f, 32.f},
    {"pin", 0.f, 160.f, 32.f, 32.f},
    {"panel_left", 32.f, 160.f, 32.f, 32.f},
}};

} // namespace hanabi::icons
