#!/usr/bin/env python3
"""Generate src/ui/icons_ink.h: each atlas icon's INK box inside its cell.

afterhours_gaps.md #114: icons::draw_fg sizes a sprite by its BOX (draw_px),
but what a design matches is the sprite's INK, and nothing relates the two --
Lucide normalises to a 24-unit box, so one nominal size draws `plus` at 12x12
and `gear` at 10x12. Sizing a mark to a measured target was build, shoot,
measure, scale, build again. This reads the committed atlas once and writes
the ink box of every icon (pixels with alpha >= 128, the ones that read as
ink), so icons::draw_px_for_ink(name, px) can answer in one step.

Run:   python3 scripts/gen_icon_ink.py          (writes the header)
       python3 scripts/gen_icon_ink.py --check  (exit 1 when it is stale)
Needs Pillow.
"""
import os
import re
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
ATLAS_PNG = os.path.join(REPO, "resources", "icons", "icons.png")
ATLAS_H = os.path.join(REPO, "src", "ui", "icons_atlas.h")
OUT_H = os.path.join(REPO, "src", "ui", "icons_ink.h")
THRESHOLD = 128


def entries():
    pat = re.compile(r'\{"([a-z_0-9]+)", ([0-9.]+)f, ([0-9.]+)f, ([0-9.]+)f, ([0-9.]+)f\}')
    with open(ATLAS_H) as f:
        for m in pat.finditer(f.read()):
            yield m.group(1), *(int(float(v)) for v in m.groups()[1:])


def render():
    im = Image.open(ATLAS_PNG).convert("RGBA")
    a = im.getchannel("A")
    rows = []
    for name, x, y, w, h in entries():
        cell = a.crop((x, y, x + w, y + h)).point(lambda v: 255 if v >= THRESHOLD else 0)
        box = cell.getbbox()
        if box is None:
            box = (0, 0, w, h)
        ix, iy, ix2, iy2 = box
        rows.append(f'    {{"{name}", {w}, {ix}, {iy}, {ix2 - ix}, {iy2 - iy}}},')
    body = "\n".join(rows)
    return f"""// AUTO-GENERATED by scripts/gen_icon_ink.py from resources/icons/icons.png
// -- do not edit by hand; rerun it when the atlas changes (source_checks
// fails while this is stale).
//
// Each icon's INK box inside its atlas cell (alpha >= {THRESHOLD}), so a mark can be
// sized by the ink a design measures rather than by its box
// (afterhours_gaps.md #114).
#pragma once
#include <array>
#include <string_view>

namespace hanabi::icons {{

struct InkEntry {{
    std::string_view name;
    int cell;               // the cell's side, in atlas pixels
    int x, y, w, h;         // the ink box, in atlas pixels, inside the cell
}};

inline constexpr std::array<InkEntry, {len(rows)}> kInk = {{{{
{body}
}}}};

inline constexpr const InkEntry* ink_of(std::string_view name) {{
    for (const InkEntry& e : kInk)
        if (e.name == name) return &e;
    return nullptr;
}}

// The draw_px that makes `name`'s ink `inkPx` tall (or wide, when `wide`):
// one step instead of build, shoot, measure, scale, rebuild. An unknown
// name answers `inkPx` (box = ink, the old assumption).
inline constexpr float draw_px_for_ink(std::string_view name, float inkPx, bool wide = false) {{
    const InkEntry* e = ink_of(name);
    if (e == nullptr) return inkPx;
    const int ink = wide ? e->w : e->h;
    if (ink <= 0) return inkPx;
    return inkPx * static_cast<float>(e->cell) / static_cast<float>(ink);
}}

// What a SCREENSHOT measures is wider than the core ink: the atlas is
// sampled down bilinearly, so partial coverage spreads about 0.75 pt past each
// edge. Calibrated on the two close-mark captures afterhours_gaps.md #114
// records (draw 11 -> 10-11 px visible; draw 8 -> 8 px), +-1 px. The draw_px
// whose VISIBLE extent is `extentPx`:
inline constexpr float kSampleSpreadPx = 1.5f;
inline constexpr float draw_px_for_extent(std::string_view name, float extentPx, bool wide = false) {{
    const float core = extentPx - kSampleSpreadPx;
    return draw_px_for_ink(name, core > 1.0f ? core : 1.0f, wide);
}}

}}  // namespace hanabi::icons
"""


def main():
    text = render()
    if "--check" in sys.argv:
        try:
            with open(OUT_H) as f:
                current = f.read()
        except FileNotFoundError:
            current = ""
        if current != text:
            print("gen_icon_ink: src/ui/icons_ink.h is stale -- run python3 scripts/gen_icon_ink.py")
            return 1
        print("gen_icon_ink: src/ui/icons_ink.h matches the atlas")
        return 0
    with open(OUT_H, "w") as f:
        f.write(text)
    print(f"gen_icon_ink: wrote {OUT_H}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
